### ISSUE TITLE
SPIKE: Estimate effort for Traefik based ephemeral environments

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/web#10086]
https://diyor28.medium.com/feature-branch-testing-with-github-actions-and-traefik-b27936ec2a7e

**Comment by nutrina** [comment]
### Plan - How to achieve this
#### Prerequisites
- a machine (EC2) with docker & docker-compose installed
- machine should be accessible via a host (like `test.gitcoin.co`)

#### Steps
1. create an external docker network: `docker network create gitcoin`
2. fire up traefik in docker, using this `docker-compose.yml`:
```
version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --accesslog=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - gitcoin

networks:
  gitcoin:
    external: true
```

3. Now you can fire up any service using another `docker-compose.yml`, and expose it on the same host, by simply including the proper docker labels, and running them on the proper network. B
```
version: '3'

services:

  web:
    # A container that exposes an API to show its IP address
    image: nginx
    
    labels:
      - "traefik.http.routers.web.rule=Host(`web.dev.iakobinyi.com`)"

    networks:
      - gitcoin


  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    
    ports:
      - 8081:80

    labels:
      - "traefik.http.routers.me.rule=Host(`me.dev.iakobinyi.com`)"

    networks:
      - gitcoin


networks:
  gitcoin:
    external: true
```
