### ISSUE TITLE
Database files not compatible with Postgres 10.x

### ISSUE THREAD

**Issue by jasonrhaas** [gitcoinco/web#78]
The docker-compose.yml file specifies the latest version of Postgres.  However, currently the database files are not compatible with  the latest Postgres.  I get this error message when running Postgres 10.1:

```
db_1   | 2017-12-04 19:13:59.586 UTC [1] FATAL:  database files are incompatible with server
db_1   | 2017-12-04 19:13:59.586 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 10.1.
```

A quick fix is to update the docker-compose.yml file to use version 9 of Postgres.

```
...
services:
  db:
    image: postgres:9
    volumes:
      - pgdata:/var/lib/postgresql/data
...
```

A better option is to update the database files so they work with Postgres 10.x.
